"$schema" = 'https://starship.rs/config-schema.json'
# Disable the blank line at the start of the prompt
add_newline = false
follow_symlinks = false
scan_timeout = 100
command_timeout = 550 

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$golang\
$java\
$package\
$nodejs\
$python\
$ruby\
$fill\
$kubernetes\
$aws\
\n$character
"""
palette = "catppuccin_mocha"
[fill]
symbol = ' '

[directory]
format = "[ $path ]($style)"
truncation_length = 4

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "
"code" = "󰲋 "
"Others" = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[aws]
format = '[$profile(\[$duration\])]($style) '
# style = "dimmed yellow"
style = "bright-black"

[bun]
format = ' [$symbol($version)]($style) '

[c]
format = ' [$symbol($version(-$name))]($style) '

[cmake]
format = ' [$symbol($version)]($style) '

[cmd_duration]
format = ' [⏱ $duration]($style) '

[cobol]
format = ' [$symbol($version)]($style) '

[conda]
format = ' [$symbol$environment]($style) '

[crystal]
format = ' [$symbol($version)]($style) '

[daml]
format = ' [$symbol($version)]($style) '

[dart]
format = ' [$symbol($version)]($style) '

[deno]
format = ' [$symbol($version)]($style) '

[docker_context]
format = ' [$symbol$context]($style) '

[dotnet]
format = ' [$symbol($version)(🎯 $tfm)]($style) '

[elixir]
format = ' [$symbol($version \(OTP $otp_version\))]($style) '

[elm]
format = ' [$symbol($version)]($style) '

[erlang]
format = ' [$symbol($version)]($style) '

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
# symbol = "[](base) "
# style = "fg:lavender bg:base"
# format =  "  [$symbol$branch]($style)[](base)"
format = ' [$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = ' [$symbol($version)]($style) '

[guix_shell]
format = ' [$symbol]($style) '

[haskell]
format = ' [$symbol($version)]($style) '

[haxe]
format = ' [$symbol($version)]($style) '

[helm]
format = ' [$symbol($version)]($style) '

[hg_branch]
format = ' [$symbol$branch]($style) '

[hostname]
ssh_only = true
ssh_symbol = '⚆ '
style = 'bold dimmed purple'

[java]
format = ' [$symbol($version)]($style) '

[julia]
format = ' [$symbol($version)]($style) '

[kotlin]
format = ' [$symbol($version)]($style) '

[kubernetes]
format = ' [$symbol$context( \($namespace\))]($style) '
disabled = false
style = "bright-black"

[lua]
format = ' [$symbol($version)]($style) '

[memory_usage]
format = ' $symbol[$ram( | $swap)]($style) '

[meson]
format = ' [$symbol$project]($style) '

[nim]
format = ' [$symbol($version)]($style) '

[nix_shell]
format = ' [$symbol$state( \($name\))]($style) '

[nodejs]
format = ' [$symbol($version)]($style) '

[ocaml]
format = ' [$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[opa]
format = ' [$symbol($version)]($style) '

[openstack]
format = ' [$symbol$cloud(\($project\))]($style) '

[os]
format = ' [$symbol]($style) '

[package]
format = ' [$symbol$version]($style) '

[perl]
format = ' [$symbol($version)]($style) '

[php]
format = ' [$symbol($version)]($style) '

[pulumi]
format = ' [$symbol$stack]($style) '

[purescript]
format = ' [$symbol($version)]($style) '

[python]
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
python_binary = ["./.venv/bin/python", "python3", "python", "python2"]

[raku]
format = ' [$symbol($version-$vm_version)]($style) '

[red]
format = ' [$symbol($version)]($style) '

[ruby]
format = ' [$symbol($version)]($style) '

[rust]
format = ' [$symbol($version)]($style) '

[scala]
format = ' [$symbol($version)]($style) '

[spack]
format = ' [$symbol$environment]($style) '

[sudo]
format = ' [as $symbol] '

[swift]
format = ' [$symbol($version)]($style) '

[terraform]
format = ' [$symbol$workspace]($style) '

[time]
format = ' [$time]($style) '
disabled = false
style = "bright-black"

[username]
format = ' [$user]($style) '

[vagrant]
format = ' [$symbol($version)]($style) '

[vlang]
format = ' [$symbol($version)]($style) '

[zig]
format = ' [$symbol($version)]($style) '
