# https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
SPACESHIP_AWS_SHOW=false
SPACESHIP_AWS_SYMBOL="⎀"

SPACESHIP_CHAR_PREFIX=''
SPACESHIP_CHAR_SUFFIX=' '
SPACESHIP_CHAR_SYMBOL="❯❯"
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_EXEC_TIME_SHOW=false
SPACESHIP_GIT_PREFIX=""
SPACESHIP_KUBECONTEXT_NAMESPACE_SHOW=false
SPACESHIP_KUBECONTEXT_PREFIX=""
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_KUBECTL_PREFIX="at "
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_SYMBOL="☸️ "
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_NODE_PREFIX=""
SPACESHIP_NODE_SHOW=true
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_VI_MODE_SHOW=false

alias kcon='export SPACESHIP_KUBECONTEXT_SHOW=true'
alias kcoff='export SPACESHIP_KUBECONTEXT_SHOW=false'
