return {}
-- return {
--   "github/copilot.vim",
--   opts = {
--     ["*"] = false,
--     ["javascript"] = true,
--     ["typescript"] = true,
--     ["lua"] = true,
--     ["rust"] = true,
--     ["go"] = true,
--     ["python"] = true,
--     ["bash"] = true,
--   },
-- }
